# Generated by Django 5.2.7 on 2025-10-17 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HealthLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('steps', models.PositiveIntegerField(default=0)),
                ('calories', models.FloatField(default=0.0)),
                ('water_intake', models.FloatField(default=0.0, help_text='Litres of water consumed')),
                ('sleep_hours', models.FloatField(default=0.0, help_text='Hours of sleep')),
            ],
        ),
    ]
