# Generated by Django 5.2.7 on 2025-10-18 07:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='healthlog',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='sleep_hours',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='steps',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='healthlog',
            name='water_intake',
            field=models.FloatField(default=0),
        ),
    ]
